---
name: flutter_prime_example
description: >-
  An example project that showcases the `flutter_prime` package.

# Contact Info
homepage: https://gizmos.dev/
repository: https://github.com/GizmosDev/flutter_prime
issue_tracker: https://github.com/GizmosDev/flutter_prime/issues

version: 0.2.0
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  prime: ^0.2.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  flutter_prime:
    path: ../

  cupertino_icons: ^1.0.8

  # Linting
  flutter_lints: ^6.0.0

  # Building
  dependency_validator: ^5.0.2

flutter:
  uses-material-design: true
