---
name: flutter_prime
description: >-
  A library of useful, reusable, methods and extensions for Flutter.

# Contact Info
homepage: https://gizmos.dev/
repository: https://github.com/GizmosDev/flutter_prime
issue_tracker: https://github.com/GizmosDev/flutter_prime/issues

version: 0.0.1-alpha.5

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  prime: ">=0.0.1-alpha.4 <0.0.1-alpha.9"

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^4.0.0

  # Building
  dependency_validator: ^4.1.0

flutter:
