---
name: flutter_prime
description: >-
  A library of useful, reusable, methods and extensions for Flutter.

# Contact Info
homepage: https://gizmos.dev/
repository: https://github.com/GizmosDev/flutter_prime
issue_tracker: https://github.com/GizmosDev/flutter_prime/issues

version: 0.1.0-alpha.6

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  prime: ^0.1.0-alpha.6

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Building
  dependency_validator: ^5.0.2

flutter:
  generate: true
